language: go

os:
  - linux

go:
  - 1.13.x

git:
  depth: 1

notifications:
  email: false

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get update -y;
        sudo apt-get install libxi-dev libxinerama-dev libxcursor-dev libxrandr-dev libgl1-mesa-dev -y;
    fi

install:
  - go get -t ./...